name: Publish to PyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Déclenche le workflow pour les tags versionnés (par exemple v0.1.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Spécifiez la version de Python que vous souhaitez utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build the package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__  # Utilisez __token__ pour l'authentification
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}  # Stockez votre jeton API dans les secrets GitHub
      run: twine upload dist/*